[package]
name = "daima_common"
version = "0.1.0"
edition = "2021"

[dependencies]
fslock = "0.2.1"
log.workspace = true
anyhow.workspace = true
rmp-serde = "1.3.0"
serde = { version = "1.0.215", features = ["derive"] }
thiserror = "2.0.3"
